name: build-manifest
on:
  push:
    branches: [ main, master ]
    paths:
      - "data/**.txt"
      - "scripts/**"
      - "package.json"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build:manifest
      - name: Commit site assets
        run: |
          if [[ -n "$(git status --porcelain site/)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add site/manifest.json site/data/ site/frases.txt
            git commit -m "chore: publish data and manifest"
            git push
          else
            echo "No changes"
